### ISSUE TITLE
Category page is unstyled

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#111]
If you click on a category link, you end up on a page that has not been styled: 

![screen shot 2016-09-12 at 12 05 09 pm](https://cloud.githubusercontent.com/assets/4327102/18443188/bf4c668c-78e1-11e6-8cfb-0062e8109c8c.png)

Category page should match News listing: 

![screen shot 2016-09-12 at 12 09 45 pm](https://cloud.githubusercontent.com/assets/4327102/18443224/ed74ed0e-78e1-11e6-8fd8-3e153033796f.png)

...but have an additional Category header at the top to indicate which category is being displayed.

**Comment by hllavina** [comment]
Completed
