### ISSUE TITLE
Add Excerpt field to Exhibits

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#118]
See https://mitlibraries.atlassian.net/browse/NTI-51

Currently the exhibits summary strips all formatting. Example: 

![screen shot 2016-12-13 at 11 40 21 am](https://cloud.githubusercontent.com/assets/4327102/21149313/215f88a6-c129-11e6-94d0-da4c46a35f98.png)

However, we would like formatting to be available to the summary so we need to add an explicit Excerpt field to the Exhibit post type to allow for this.

**Comment by hllavina** [comment]
Completed with merge to master
