### ISSUE TITLE
Header image is misaligned and squished

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#16]
The new child header image displays only the top part of the image - it should display center center so the middle of the image shows. Also, when viewing smaller screen sizes like for mobile, the image gets squished instead of cropped. 

Desktop Ok:
![screen shot 2016-06-08 at 4 13 16 pm](https://cloud.githubusercontent.com/assets/4327102/15909367/0eecb910-2d94-11e6-93e0-6c8f4ae91376.png)

Mobile Squished:
![screen shot 2016-06-08 at 4 13 30 pm](https://cloud.githubusercontent.com/assets/4327102/15909369/11dd2ec0-2d94-11e6-9dea-448b8025ddeb.png)

Mobile Ok:
![screen shot 2016-06-08 at 4 13 52 pm](https://cloud.githubusercontent.com/assets/4327102/15909373/144416e2-2d94-11e6-973c-13f8200e0c35.png)

**Comment by PBruk** [comment]
Fixes #16 and fixes #17. Word completed. PR submitted. Ideal header image should now be 1250 x 800 px or if a smaller image, a ratio of 25:16, .64, or 1.56.

**Comment by frrrances** [comment]
Resolved with https://github.com/MITLibraries/MITLibraries-child/commit/d2f6882
