### ISSUE TITLE
Featured image should be centered

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#17]
When a featured image is added to a page, it is only showing the very top, but it needs to be centered to show the middle of the image. It also gets squished.

If possible, it would be nice to have some dimensions or help text with the featured image setting in the admin area.

Current: 
![screen shot 2016-06-08 at 4 24 07 pm](https://cloud.githubusercontent.com/assets/4327102/15909816/0c27adfa-2d96-11e6-8b70-212e09df8677.png)

Preferred:
![screen shot 2016-06-08 at 4 31 20 pm](https://cloud.githubusercontent.com/assets/4327102/15909883/7697de12-2d96-11e6-843c-224e022adac6.png)

Squished:
![screen shot 2016-06-08 at 4 32 11 pm](https://cloud.githubusercontent.com/assets/4327102/15909938/d075a356-2d96-11e6-84f3-42d918a9d431.png)

Ok:
![screen shot 2016-06-08 at 4 33 42 pm](https://cloud.githubusercontent.com/assets/4327102/15909945/d71f8b86-2d96-11e6-858e-f8ac9cd61881.png)

**Comment by PBruk** [comment]
I addressed this as part of issue #16

**Comment by frrrances** [comment]
Merged with and replaced by #16
