### ISSUE TITLE
Text is too tight

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#18]
The headers and text line-heights, margin, and/or padding are too tight. It is most obvious on this text-heavy page:

https://libraries-test2.mit.edu/giving/opportunities/people/

![tight-copy](https://cloud.githubusercontent.com/assets/4327102/15910179/c203ca4a-2d97-11e6-9004-293c69d5f521.png)

Header is too close to text, line-height in paragraph is too tight, space before and after lists and list items is too small.

**Comment by PBruk** [comment]
If you look at this page, with the latest Child branch (mostly) it looks fine: https://libraries-dev.mit.edu/giving/opportunities/people/

sidenote: for testing purposes, I switched to child-new theme, yesterday, as opposed to the transition theme, the Dev site was using.

**Comment by frrrances** [comment]
Holding off on changes to fix this until we have a cleaner test environment.

**Comment by frrrances** [comment]
I rolled this in with some other changes in #44
