### ISSUE TITLE
Convert /collections to Child theme

### ISSUE THREAD

**Issue by PBruk** [MITLibraries/MITLibraries-child#4]

**Comment by PBruk** [comment]
Have begun conversion... will wait for feedback on some questions I have. In meanwhile, need to fix breadcrumbs.

**Comment by darcyduke** [comment]
Bunch of things we need to straighten out, but it's a start! Let's chat.

**Comment by matt-bernhardt** [comment]
I'm wondering if the issues we're running into with adapting new sites to this theme have to do with the current code being too tightly coupled to specific site content? Or are they something else?

**Comment by darcyduke** [comment]
Hmm, I don't think so - in this case we are trying to add a new feature that many sites would like to have.

**Comment by matt-bernhardt** [comment]
Ah, so the issues for /collections have to do with the custom post types that we talked about around /exhibits?

**Comment by darcyduke** [comment]
I think Collections will be an easier migration than most, Phillip just hasn't been focused on it yet.

**Comment by darcyduke** [comment]
Resolving this since Stephanie and Frances will be working on this (not a development issue at this point).
