### ISSUE TITLE
AKDC News page is not showing posts

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#40]
The main content area on the AKDC site is empty (on -dev and -test), but there are valid posts.

**Comment by PBruk** [comment]
This was a content setting issue. For some reason this page was set to Posts in the Customizer, but it's an actual page that uses the Ultimate Posts Widget to populate all the posts.

https://snag.gy/C7nSme.jpg

**Comment by frrrances** [comment]
Thanks for the info, @PBruk ! closing this since it doesn't need code to fix...
