### ISSUE TITLE
Header image goes out of box on IE

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#57]
The header image is going out of the grid on home and subpages. 

![pasted image at 2016_06_22 01_23 pm-1](https://cloud.githubusercontent.com/assets/4327102/16276496/a7895640-387c-11e6-84d1-2833cbb3dc9f.png)

![pasted image at 2016_06_22 01_23 pm](https://cloud.githubusercontent.com/assets/4327102/16276501/aa8bef92-387c-11e6-91a7-69e3580fb9a3.png)

**Comment by PBruk** [comment]
Yeah, I noticed that problem when I was testing on BrowserStack - which is why that hard width of 1020px was kept. I have tried adding an IE media query conditional to test out now, but BrowserStack is giving me fits, so... will check in office tomorrow morn.
