### ISSUE TITLE
Questions about breadcrumbs

### ISSUE THREAD

**Issue by matt-bernhardt** [MITLibraries/MITLibraries-child#7]
I'm curious about our approach to breadcrumbs in this theme (and perhaps more generally across the other themes). The accessibility best practices I'm familiar with call for breadcrumbs to be treated slightly differently than we are currently.

**Comment by matt-bernhardt** [comment]
An example of the approach I've heard favored by some is to structure the breadcrumb as a sentence. So what might display would be:

`Home > Locations > Barker Library`

But what the user would hear would be:

`You are in section Locations, on page Barker Library`

It looks like the KSA is still using the Drupal module I built to achieve this - if you look at http://knowlton.osu.edu/mcrp and inspect the page for div.ksa-breadcrumb:

```
<div class="ksa-breadcrumb">
  <span class="osu-semantic">You are in section </span>
  <span class="breadcrumb-root"><a href="/programs/city-and-regional-planning">City and Regional Planning</a></span>
  <span class="osu-semantic">,  on page </span>
  <span class="breadcrumb-you"><a href="/mcrp" class="active">Master</a></span>
  <span class="osu-semantic">.  From here you can visit:</span>
  <span class="breadcrumb-children">
    <ul>
      <li><a href="/programs-and-admissions-city-and-regional-planning-mcrp/curriculum">Curriculum</a></li>
      <li><a href="/academic-programs-city-and-regional-planning-master-curriculum/dual-degrees">Dual Degrees</a></li>
      <li><a href="/programs-and-admissions-city-and-regional-planning-mcrp-curriculum/internships">Internship Program</a></li>
      <li><a href="/academic-programs-city-and-regional-planning-master/student-profiles">Student Profiles</a></li>
      <li><a href="/academic-programs-city-and-regional-planning-master/alumni-profiles">Alumni Profiles</a></li>
      <li><a href="http://knowlton.osu.edu/student-gallery/#filter=.master.city-and-regional-planning">Student Work</a></li>
    </ul>
  </span>
  <span class="osu-semantic"> </span>
</div>
```

**Comment by darcyduke** [comment]
Matt, I don't think this seems pressing for now so I'm going to close it  - we can think about it later if we do some major work around the breadcrumbs/headers, etc.
