### ISSUE TITLE
Duplicate stylesheets being loaded

### ISSUE THREAD

**Issue by matt-bernhardt** [MITLibraries/MITLibraries-child#8]
Sites on the child theme seem to be loading the parent's stylesheet twice. 

Once here:
https://github.com/MITLibraries/MITLibraries-child/blob/master/functions.php#L16
under the name 'roger' (wat?) and once here:
https://github.com/MITLibraries/MITLibraries-child/blob/master/style.css#L12

More confusingly, at least based on the order in the "Edit CSS" pane on FF's Web Developer toolbar, they seem to straddle the child theme's rules - which given the vagaries of the cascade may result in who-knows-what weirdness.

For now, @PBruk has resolved the situation on -dev in favor of the '@ import' line in the child stylesheet - which is also how we do it in Courtyard-Blog. I'd like to think about this a bit more, however, for deciding that this is the canonical approach for our child themes.

Tagging @darcyduke @frrrances for their thoughts.

**Comment by matt-bernhardt** [comment]
One issue is that the method used in functions.php, `get_template_directory_uri()` is a bit hackish in that the path it outputs isn't _actually_ the right path to the stylesheet. Wordpress resolves it fine, but rather than

`/wp-content/themes/libraries/style.css` 
the path is
`/giving/wp-content/themes/libraries/style.css`

This strikes me as less than optimal, but this may be a case of me being too fastidious for my own good.

https://wordpress.org/support/topic/child-theme-returning-partent-themes-file-pate

**Comment by darcyduke** [comment]
Hmm, Matt, I don't think I have the expertise to help decide which is the best way to resolve this. If you clarify the pros/cons of the different ways of dealing with this, I'm happy to add my $.02, but I also trust you to make the best decision.

**Comment by matt-bernhardt** [comment]
The WordPress Codex clarifies this question - unfortunately not in the direction that we had moved:

`The final step is to enqueue the parent and child theme stylesheets. Note that the previous method was to import the parent theme stylesheet using @import: this is no longer best practice. The correct method of enqueuing the parent theme stylesheet is to add a wp_enqueue_scripts action and use wp_enqueue_style() in your child theme's functions.php.`
-- https://codex.wordpress.org/Child_Themes

Given this, we should make sure that all our child themes are loading the parent stylesheet via functions.php.

**Comment by frrrances** [comment]
Nice find, @matt-bernhardt! Sounds like the best direction to me.

**Comment by PBruk** [comment]
Closed as per WP Codex quoted above.

**Comment by frrrances** [comment]
@PBruk are there any other child themes we should fix or is it just the new one?
