### ISSUE TITLE
headers 1-3 too light on home

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#82]
The headers on the homepage are different (lighter font-wieght) than the rest of the site. They should be the same, and there should be a class to adjust them for particular cases. (see MIT Reads site: https://libraries-test.mit.edu/mit-reads/)

**Comment by PBruk** [comment]
This issue was moved/recreated in the Parent theme as issue #161, so am thinking this can be closed here?

**Comment by frrrances** [comment]
Yup! fixed on parent.
