### ISSUE TITLE
Single page issues

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#84]
Exhibits single post page is showing the “News” header, post date and the header image seem to be missing. (This is probably a result of the adjustments we made for Scholarly Publishing - can we have both cases?)

**Comment by PBruk** [comment]
The header image was missing because of the servers being down.

This issue is being amended to replace the post date with the starting and ending date of the exhibit.

**Comment by frrrances** [comment]
I found a screenshot of what the page used to look like (see below). Can we add in the things that went missing? Location, dates, sponsor, and subtitle. Also, can we put the image in the template as well? I know we went back and forth on that but I think it is nice to have it included automatically. 

![example-subtitle](https://cloud.githubusercontent.com/assets/4327102/18010716/bb94ccb0-6b7f-11e6-8dd3-94a170e2b91a.png)
