### ISSUE TITLE
Add “Show all” filter option

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#88]
When a location filter is applied, there is no way to go back to seeing all locations - we need to add a “Show all” option in sidebar below Maihaugan and Rotch.

**Comment by PBruk** [comment]
This gets done in WP Admin under menus:

![show-all-filter](https://cloud.githubusercontent.com/assets/1832277/17906832/f416830c-6946-11e6-8d37-4d31910ad17c.png)

Just click on **Current, Upcoming, and Past Exhibits** and **Add to Menu** and change the navigation label to show all...
