### ISSUE TITLE
Featured image doesn’t show on detail exhibits page

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/MITLibraries-child#89]
The featured image isn't showing on the detail exhibits page - it should default to show the site header image or show a set featured image.

**Comment by PBruk** [comment]
I believe this was as an issue on -test.

I was able to add a featured image on -dev and it showed and if no featured image was added, then the default image shows.

![fis](https://cloud.githubusercontent.com/assets/1832277/17907048/eb3b4442-6947-11e6-9a08-1cd9bfc4f3b5.png)

![nfis](https://cloud.githubusercontent.com/assets/1832277/17907055/ef890e12-6947-11e6-88a8-32e437b1581e.png)

**Comment by frrrances** [comment]
Yup, working fine now.
